### ISSUE TITLE
Support new menu system type buttons

### ISSUE THREAD

**Issue by splitbrain** [Klap-in/dokuwiki-plugin-bookcreator#104]
The way how menus are built will change in the next DokuWiki release (see https://www.patreon.com/posts/menus-14160215). The plugin should be adjusted to add its button through the new MENU_ITEMS_ASSEMBLY event.

**Comment by Klap-in** [comment]
@splitbrain implemented using more paths in the svg, to let the icon toggle its state depending whether the page was added to book, these new pagetools are nice stuff!
