### ISSUE TITLE
Need separated book templates with setup ACL

### ISSUE THREAD

**Issue by xmoonlight** [Klap-in/dokuwiki-plugin-bookcreator#112]
Need separated book templates for user groups and for each user with setup ACL (view, change, remove).

**Comment by Klap-in** [comment]
Pages without read permission should be excluded during the export

If I remember right, the list of save selections respect permissions of the page at which the selection is stored as well. So If the selection page has permission it should be displayed. 

At the moment no ACL rules dependent templates are possible.

**Comment by xmoonlight** [comment]
I needed separated templates between users: for one user - his book templates (his list of pages of book), for other users - other templates, and etc. 
For each user: its own set of templates and pages in them (with correct ACL compliance for accessing pages for setting up a regular template by a specific user).

**Comment by Klap-in** [comment]
I do not get exactly what you need. But so far I understand, it is a way too complex for a tool like this.
