### ISSUE TITLE
Fatal error: Interface 'Psr\Log\LoggerAwareInterface' not found in ...\lib\plugins\dw2pdf\vendor\mpdf\mpdf\src\Mpdf.php on line 56

### ISSUE THREAD

**Issue by Black-Magic** [Klap-in/dokuwiki-plugin-bookcreator#114]
I am unable to create a PDF. 

After clicking on the button "Export" with "Export selection to PDF" in the drip down chosen, 
A pop up come up displaying "We are preparing your download, please wait... "

It then changes to "Fatal error: Interface 'Psr\Log\LoggerAwareInterface' not found in <snipped valid path to file>\lib\plugins\dw2pdf\vendor\mpdf\mpdf\src\Mpdf.php on line 56"

**Comment by micgro42** [comment]
Please ensure that both bookcreator plugin and dw2pdf plugin are up-to-date. Especially dw2pdf had an update yesterday.

If the error persists could you tell us your PHP version, your DokuWiki version and what server you are using?

**Comment by Klap-in** [comment]
I cannot reproduce this case.

**Comment by Black-Magic** [comment]
I'm on: 
Apache/2.4.25(Win32)
PHP 5.6.30
Release 2017-02-19e "Frusterick Manners"
Just got Dw2Pdf update 2018-03-30    ......... and now it is working.

I guess mark this as closed?

**Comment by AckiIsMe** [comment]
Same Issue:
blanc page after Export to PDF
error-log like above but line 55
dw2pdf Update:2018-04-23
no bookcreator
Dokuwiki: 2018-04-22 "Greebo"
php 7.1.8
httpd24 2.4.27
Rhel 7.4

**Comment by Klap-in** [comment]
Did you also try to reinstall the dw2pdf plugin and bookcreator plugin?

**Comment by AckiIsMe** [comment]
reinstall did the job!
Thank you!
