### ISSUE TITLE
Plugin assumes that main content from the page is into #dokuwiki__content element

### ISSUE THREAD

**Issue by eduardomozart** [Klap-in/dokuwiki-plugin-bookcreator#131]
The Bookcreator plugin fails to load the pages added to the book into "Create PDF book" page into Vector template because it assumes that the page content is into ``#dokuwiki__content``, but Vector template uses ``#content``. I create a pull request into Vector template to address this issue: https://github.com/arsava/dokuwiki-template-vector/pull/66

But I believe that Bookcreator should use another method instead of relying into a preset HTML element name, or maybe offer the possibility to configure it's element name into plug-in options.

**Comment by Klap-in** [comment]
Unfortunately, the vector template lacks or has very delayed maintainance. Having a quick look, I think #dokuwiki__content is rather common for templates of DokuWiki. But I see it is used here for a very trivial thing, so I changed that. As bonus I improved the position of the dialog to be relative to the Add Namespace button.
