### ISSUE TITLE
Template artictut and bookcreator

### ISSUE THREAD

**Issue by docmoritz** [Klap-in/dokuwiki-plugin-bookcreator#133]
Any idea how to change the template easy way to get bookcreator to work?
https://www.dokuwiki.org/template:arctictut
When I use this template the ebook page structure is not shown...
Original Theme works great...
tx
Peter
![2021-07-19 13_58_03-wiki_ebook  Respektfilm - Unternehmensdokumentation](https://user-images.githubusercontent.com/16244998/126156646-5dcf3f9c-3ff4-4309-b82c-735307828fb0.jpg)
![2021-07-19 13_58_35-wiki_ebook  Respektfilm - Unternehmensdokumentation](https://user-images.githubusercontent.com/16244998/126156649-e3ea1727-f74a-4cf7-9d50-3ccae94f7551.jpg)

**Comment by Klap-in** [comment]
I tried to reproduce your situation. With the Arctictut template the list shows up as expected for me. Could you check if you use the last versions?
