### ISSUE TITLE
SNAPSHOT OF A NAMESPACE - dokuwiki for documentation: just export the content of a current namespace (no saved selections)

### ISSUE THREAD

**Issue by Chris75forumname** [Klap-in/dokuwiki-plugin-bookcreator#135]
Hi,
since we are using dokuwiki for documentation, I need the functionality to export a current namespace without further ado.
There should be a simple export link syntax, like `~~PDFNS>namespace|pdftitle~~`, see: https://www.dokuwiki.org/plugin:dw2pdf#syntax. Something like: `~~HTMLNS>namespace|Link~~` (as previously requested here: https://github.com/Klap-in/dokuwiki-plugin-bookcreator/issues/125#issuecomment-640229983)

All the while, I wrote myself a nice little click-bot, who works like a charm:
```
    jQuery(function(){
       if( jQuery("h1#export_manager_my_project").length > 0 ) {
          setTimeout(function() { jQuery("button[name='resetselection']")[0].click();
             setTimeout(function() { jQuery("button[name='selectns']")[0].click();
                setTimeout(function() { jQuery("a[title='namespace:my_project:milestones:']")[0].click();
                   setTimeout(function() { jQuery("#bc__nspicker_select")[0].click();
                      setTimeout(function() { jQuery("button[name='exportselection']")[0].click(); 
                      }, 200);
                   }, 200);
                }, 400);
             }, 0);
          }, 0);
       }
    });

```

**Comment by Klap-in** [comment]
You can already export your namespace with `~~PDFNS>namespace|pdftitle~~`. I don’t understand what is different in your proposal… Could please explain the difference?

**Comment by Chris75forumname** [comment]
As I said above `~~HTMLNS>namespace|Link~~`, I need the same for HTML export.

**Comment by Nif9** [comment]
I have almost the same need : export a full namespace. But I also want to reorder it or delete few pages from a huge selection.

Can the book manager be enriched by a text input allowing to input page names or namespace (mynamespace:*) with a "add" button? 

Thank you.
