### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [Klap-in/dokuwiki-plugin-bookcreator#138]
Hello,

when I export many pages as TEXT (text plugin) with Bookcreator, I get the error message "Maximum execution time of 30 seconds exceeded". If I export the same selection to PDF, everything is fine. 

Can I influence this without setting PHP's 30-second limit high?

With kind regards
Juergen

**Comment by Klap-in** [comment]
On all kind of pages, also, for example on the wiki:syntax page? 
or is a page with a one-liner already enough?

**Comment by Juergen-aus-Zuendorf** [comment]
This is only the case when I use the Bookcreator with a selection of many pages. If I reduce the number of pages, everything works.
I am wondering how the PDF creation with the same number of pages works without any problems.

**Comment by Klap-in** [comment]
This is limit set for your PHP. If needed, you might consider increasing it in the settings of PHP. It is a limitation of exporting large amount of pages via a php based tool.
