### ISSUE TITLE
bookcreator missing on pages

### ISSUE THREAD

**Issue by helm71** [Klap-in/dokuwiki-plugin-bookcreator#144]
I was creating a book in bookcreator and all seems to work fine, there are however a few pages in my dokuwiki set that when I open them do not show the bookcreator plugin. They are not in a specific namespace and I also cannot see anything else those pages have in common.. Pages "around it" with the same level of info do show the pluggin...

What am I missing ?

**Comment by Klap-in** [comment]
Which other plugins do you use? (if you use the blogtng, at the page which shows all entries the bookbar is not shown).

Please reopen if you have more info.
