### ISSUE TITLE
Bookcreator and Move plugin

### ISSUE THREAD

**Issue by eduardomozart** [Klap-in/dokuwiki-plugin-bookcreator#145]
When moving pages through Move plugin, it would be great if Bookcreator hook an event into this moving (the Move plugin offer a hook for it) so it would be able to update the old page namespace reference to the new one instead of us having to edit manually the book to remove the old reference and add the new one.

**Comment by Klap-in** [comment]
You mean that the pages which stores the saved books are not changed by the move plugin? I guess that the move plugin will already mark these pages as affected by link update. And if I remember right it will perform such an update on (I guess) display of the page with the saved book? Or is such update not happening at all by the move plugin if you visit the page with a saved book in the normal manner?

**Comment by eduardomozart** [comment]
I mean the ones that are stored into cookies. I believe those are saved as pages should be automatically updated by the Move plugin.

**Comment by Klap-in** [comment]
With 'cookies' you mean the current active selection in your browser? Does changes with the move plugin happen that often that fixing that selection is needed?
This selection is stored in your local storage of your browser (technically no cookie ;-) ). As that is really local, it is not aware of changes in the wiki on the server. 
The move plugin uses the parsed syntax of the pages to schedule the needed page renames. As the active selection is only in the browser it cannot hook in that change handling. Therefore, I expect that implementation of this feature is only possible if the move plugin has also a log or marks the old pages in a technical readable format such that we can recognize with the bookcreator that the page is now moved, and that it should rename the pages from the active selection.

I see the move plugins logs, but not sure if that format is useful for this purpose. I have no time to investigate and implement this feature (of course pull requests are welcome).
