### ISSUE TITLE
resolve_pageid is deprecated

### ISSUE THREAD

**Issue by fjf2002** [Klap-in/dokuwiki-plugin-bookcreator#146]
My deprecated log gets spammed with messages

> resolve_pageid() is deprecated. It was called from action_plugin_bookcreator_pagetools::isVisible() in /srv/www/htdocs/doku/lib/plugins/bookcreator/action/pagetools.php:173 dokuwiki\File\PageResolver should be used instead!

* for the problem location, cf. https://github.com/Klap-in/dokuwiki-plugin-bookcreator/blob/dff4beb4b11525553550c63d4d7a2fde3349d869/action/pagetools.php#L173

* for some solution, cf. https://github.com/dokuwiki/dokuwiki/blob/7bb0ac825f6f9a87f91b1cc0fd615d7154e1c7ca/inc/pageutils.php#L574

**Comment by dzidek23** [comment]
Hi,
Same here..

`2023-07-11 10:27:59resolve_pageid() is deprecated. It was called from action_plugin_bookcreator_pagetools::isVisible() in /var/www/dokuwiki/lib/plugins/bookcreator/action/pagetools.php:173 dokuwiki\File\PageResolver should be used instead!`

Bookcreator installed version:  2021-03-30
dokuwiki 2023-04-04a "Jack Jackrum"

**Comment by fjf2002** [comment]
Thanks :-)
