### ISSUE TITLE
'Page selection problem'

### ISSUE THREAD

**Issue by Klap-in** [Klap-in/dokuwiki-plugin-bookcreator#17]
As reported at: https://www.dokuwiki.org/plugin:bookcreator:discussion

```
===== Page selection problem 1/8/2014 =====
I can select pages but when I go to save the selection I get the 
messages "You don't have pages selected yet."  I can delete pages 
selected successfully. I have verified cookies are created for each page. 
 I do not have a cookie listing the pages if it should exist.  I am wiki-admin 
with all permissions. 
FireFox 25.01
DokuWiki Weatherwax
bookcreator is current as of 1/8/2014 - no output for "Text", Printable Version or PDF
dw2pdf is current as of 8/16/2013 and works properly from URL and tab button

Edit: Same here, FF 27, fresh installation of DokuWiki, bookcreator and dw2pdf 
on XAMPP / Win7
```

**Comment by EdgeOfElfland** [comment]
I'm having this problem as well.  I'm using Dokuwiki Hrun (2014/12/08) version.

I've created the wiki:ebook page, and can see a list of selected pages with the option to export to PDF or save selection.  When I export to PDF, it says "You don't have pages selected yet."

Exporting a single page with plugin "dw2pdf" does work.

My cookies have:
DokuWiki = b063ihbc2q9gnco2cv9bplc0m4
bookcreator[arch:user-guide:basics] = 1

Browser: Firefox 31.0
Server: Windows Server 2008 R2
PHP 5.3.9

**Comment by poulpoulsen** [comment]
Hello,
unfortunately i could agree with this bug.
Perhaps a clarification:
It works, if i add pages one by one.
But NOT if i add a whole namespace (pages inside) with editing the subpage inside wiki:ebooks:
Also it is not working, if i add more than 100 pages?? Is there any limit inside?

Adding a whole pages one-by-one is boring, so a feature to add more than one will be very pleased.

Regards
Poul

**Comment by Klap-in** [comment]
The pages which are scheduled for export are stored in cookies. The maximum number is limited by the cookie size, which is determined by size of the header of the page (often somewhere between 60-80 pages are possible)

There is an export an namespace option, see docs about url parameters: https://www.dokuwiki.org/plugin:dw2pdf#configuration

Sofar I have no clue why a set of pages stored in a page in wiki:ebooks aren't working. Is the pagelist cookie available when you try to start the export?
(note: Are you sure you have set the namespace in the config to your storage namespace? `wiki:ebook` vs `wiki:ebooks`.)

**Comment by poulpoulsen** [comment]
Hello,
thank you for your quick answer.
I've thought about the namespace option, but i do not understand it.
Want i want to do.

I use one wikipage with a table in it to work.
Inside one column there are many links to other wikipages in another 
namespace

the worker wikipage is named ::garten:planung:planung_blauer_garten
the linked namespace is called ::lesezeichen:2015:
All wikipages inside this namespace are linked to the page 
::garten:planung:planung_blauer_garten, so i need the whole namespace to 
have a working copy inside the pdf.
is this possible?

Regards
Poul Poulsen


Am 03.03.2015 um 07:28 schrieb Gerrit Uitslag:

**Comment by Klap-in** [comment]
Currently the namespace export url parameters options (like: `?do=export_pdfns&dfns_ns=lesezeichen:2015&pdfns_title=Your%20title` (or eventually `&do=...`) will only export the namespace, but no additional pages.
maybe as workaround you can (a duplicate) of this page in that namespace as well?

I'm brainstorming how I can workaround the use of cookies, such that it hasn't the restrictions of a limit size any more. (However on the short term I have other priorities.)

**Comment by Klap-in** [comment]
The backend of this plugin is not based at cookies anymore but on localStorage.
You can obtain this by updating the bookcreator plugin+dw2pdf plugin.
I expect that with this new release this issue is solved as well.
