### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by cottitsch** [Klap-in/dokuwiki-plugin-bookcreator#42]
I am using dokuwiki hrun (linux on synology nas) and wheaterwax (windows server 2008R2),
Browser Firefox 33, Chrome or IE 9, cookies enabled and i have this problems with the bookcreator plugin:
Adding pages to the book works fine, when i go the wiki:ebook page i can not :
-reorder the entries,
-delete the entries
I can delete the whole selection.
After adding one page to the book the bar with "add and delete this page " appears on every page, but clicking on the links/symbols, doesn't have any effect.
Has somebody an idea?

**Comment by Klap-in** [comment]
Are you still affected by this?

**Comment by Klap-in** [comment]
Probably this due to old JavaScript in some plugin or template. Disable that or update it please.
