### ISSUE TITLE
Wrap Plugin CSS works only for the first page.

### ISSUE THREAD

**Issue by shawndibble** [Klap-in/dokuwiki-plugin-bookcreator#47]
So I use the wrap plugin with bookcreator. I have tried adding multiple pages from my wiki, each with some notification/info/alert via the wrap plugin. The first wiki page generates just fine. However after that, the CSS drops. I may be seeing a square border instead of a round or all the wrap CSS disappears and it looks like regular text. 

I have tried disabling all plugins except for the bookcreator and its dependent plugins and the wrap plugin, but still the same thing. 

Here is the print and pdf output as you can see in the PDF, this wiki page is lacking the wrap styling. However the wiki page before it will show the styling just fine.

![print](https://cloud.githubusercontent.com/assets/1980293/6399474/455e2210-bdb8-11e4-950f-d23c2ee8c06f.PNG)
![pdf](https://cloud.githubusercontent.com/assets/1980293/6399475/45611cb8-bdb8-11e4-8f48-c620e5af06b8.PNG)

---

UPDATE: I have tested this and it appears to be an issue with dw2pdf itself as it happens when I output an entire namespace as well.

**Comment by Klap-in** [comment]
Recently the mPDF library is updated to a new major version 6.0, which brings us extended css support.
Can you retry whether now these issues are improved?

**Comment by LarsGit223** [comment]
If you do not explicitly need PDF you might also try to export to ODT. Just make sure you use the latest version of all 3 plugins (bookcreator, ODT, Wrap).
