### ISSUE TITLE
Not have a page break after the end of each wiki page

### ISSUE THREAD

**Issue by cjrobe** [Klap-in/dokuwiki-plugin-bookcreator#48]
I'd like to have a continuous stream of wiki pages to save paper, is there any way to get rid of the page break at the end of each wiki page in the generated PDF?

**Comment by Klap-in** [comment]
Not on purpose.

The pagebreak in the page-loop will initiate the breaks.
You could modify it manually (however this workaround is overwritten on update..)
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L324

**Comment by cjrobe** [comment]
Thanks for the quick response. Works great!

**Comment by Klap-in** [comment]
I will not implement this. If someone is interested a pull request is welcome. Note that manual modification at every update of mpdf are not workable for us, so such solutions will not be considered.
