### ISSUE TITLE
List numbers incorrectly generated in pdf

### ISSUE THREAD

**Issue by customsystems** [Klap-in/dokuwiki-plugin-bookcreator#49]
When exporting a list.
1.
    a.
       I.
         A.
       II.
         A.
              i.
              ii.

Becomes
1.
      1.
            1.
                    1.
             2.
                     1.
                           1.
                            2.

**Comment by Klap-in** [comment]
This is probably an issue with the dw2pdf plugin, which is used in the bookcreator plugin for generating the pdfs.
