### ISSUE TITLE
Sometimes a empty message is displayed on missing title

### ISSUE THREAD

**Issue by LarsGit223** [Klap-in/dokuwiki-plugin-bookcreator#56]
If a book shall be exported to pdf or odt and the title is missing, then sometimes an empty message is displayed and sometimes the message "Please provide a title" ($lang ['needtitle']).

Here the sequence of actions in detail:
- add pages to book
- go to ebook page
- select export format 'PDF'
- click on 'export'
- empty message appears
- click on 'export' again
- message "Please provide a title" appears

I assume this might be a DokuWiki problem not a bookcreator thing. I tested it with firefox and chromium. Both have the problem.

**Comment by Klap-in** [comment]
Fixed by 3ff516339517f218d234f59ad4e457ac4c9dcd68
The ODT plugin missed some language strings.
