### ISSUE TITLE
Nothing works until you disable CSS & Javascript compression

### ISSUE THREAD

**Issue by refrain** [Klap-in/dokuwiki-plugin-bookcreator#67]
None of the features work at all UNTIL you disable this in the configuration settings:

Compress: Compact CSS and javascript output

**Comment by refrain** [comment]
For example,

Cannot export
Cannot remove an added page
Cannot drag/drop re-order
Cannot save selection

After you disable "Compress: Compact CSS and javascript output", everything works.

**Comment by Klap-in** [comment]
Is there some error in the JavaScript file that is retrieved when opening a page? You can check that by using the developer console in the browser.

**Comment by refrain** [comment]
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation (js.php:23)

The code on line 23 has something to do with jQuery Migrate but it is too long to paste here.  This is from line 21:

/*! jQuery Migrate v1.2.1 | (c) 2005, 2013 jQuery Foundation, Inc. and other contributors | jquery.org/license */

**Comment by Klap-in** [comment]
Could you download that file and sent it by mail to me? (see my github profile for my email). The file is compressed, so linebreaks are removed.
Therefore line numbers aren't that meaningful anymore.

**Comment by refrain** [comment]
I have emailed you the js.php file as an attachment from refrain5@hotmail.com.  Firefox has a different error message, but still problem with line 23 on js.php:

15:53:15.712 SyntaxError: invalid increment operand1 js.php:23:615253

**Comment by HeteMacmania** [comment]
nothing work's for me :-(
i can't even see the Help Page

http://doc.kanjo.ca/wiki/ebook_help

**Comment by Klap-in** [comment]
How is the last version of this plugin+DokuWiki behaving?

**Comment by HeteMacmania** [comment]
don’t know, i didnt do the update

**Comment by LarsGit223** [comment]
@refrain:
Did you test the latest version of DokuWiki? I remember that there was an issue in the JavaScript compression but that is about 2 years ago. Which DokuWiki version do you use?

**Comment by Klap-in** [comment]
In the past DokuWiki had some small issues with the compressor of the js or css. I would not known how these could affect this, but of course I cannot exclude that. We are some years further now.. Please could you test again with a recent updated DokuWiki, dw2pdf and bookcreator plugins? If this problem is still there, please reopen this issue.
