### ISSUE TITLE
PDF export times out with large number of chapters

### ISSUE THREAD

**Issue by halfbeing** [Klap-in/dokuwiki-plugin-bookcreator#69]
I've been trying to export a book to PDF. The chapters are short (around 400 words each with no pictures), but there are a lot of them, around 50 (my plan was to make books with hundreds of chapters). Unfortunately the process times out after 120 seconds and I get the following message:
`Fatal error: Maximum execution time of 120 seconds exceeded in C:\wamp\www\commonplace\lib\plugins\dw2pdf\mpdf\classes\otl.php on line 5438`

**Comment by Klap-in** [comment]
Hmmm since relative short time we use version 6 of the library mPDF. Could it be that since the upgrade from version 5 to 6 the export is a bit slower....

**Comment by LarsGit223** [comment]
With the new release of the ODT plugin it also has become slower. I tried to export 125 pages from DokuWiki.org to ODT and it timed out.

Of course I could not improve the speed of the plugin so I changed the PHP configuration of my PC/machine. In file ```/etc/php/7.0/apache2/php.ini``` I increased the maximum execution time to **10 minutes**:
```
; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time = 600
```
After that the ODT export was succesful. It took **7 minutes** but it completed!

My DokuWiki runs on Ubuntu using Apache2 as the web server. If you have a different operating system or web server then your directory might differ. If you run your wiki on an public web server you might have to ask the admin or web hoster to change it.

**Comment by Klap-in** [comment]
The dw2pdf plugin, used by bookcreator plugin, depends on an upstream library: mPDF library. It a complex library to maintain, they made some progress and with newer PHP version, also PHP executing improves significant. I do not know of low hanging fruit to pick for improvement. 

If more guiding is required for extending the execution time, improvement of the documentation is probably very useful.
