### ISSUE TITLE
Error 400 due to excessively long cookies

### ISSUE THREAD

**Issue by halfbeing** [Klap-in/dokuwiki-plugin-bookcreator#71]
I tried to create a book of over 50 chapters and I started getting
`Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
Cookie`

Deleting my cookies got things working again.

**Comment by Klap-in** [comment]
The implementation of issue #31 will improve this. But implementation needs more experience with local storage, what means that I will not complete that at the short term. I will close this issue as duplicate.

If have an improvement in preparation that will probably double the number of pages that could be selected, but testing that take some effort.. No idea when I will publish this improvement.
