### ISSUE TITLE
[localStorage] Can not recover saved lists 

### ISSUE THREAD

**Issue by rkhalil** [Klap-in/dokuwiki-plugin-bookcreator#78]
we were facing problems when saving a book with a long list of pages. We created a copy of our dokuwiki and replaced the files from pdfbook with the branch "localStorate". #72 

Our setup is:
- dokuwiki Release 2015-08-10a "Detritus"
- dw2pdf: date    2016-04-17
- other plugins.

We have no problems now when exporting books with many files but the problem now is we can not recover saved list (better said, we can recover the list but not continue editing).  I dont see any related errors in apache or javascript console. How Can I debug further? Or what could I test?

  ##![dokuwiki_1](https://cloud.githubusercontent.com/assets/20515302/16912688/f52d24bc-4ce5-11e6-8704-63496abf0359.png)

**Comment by Klap-in** [comment]
Which button do you use when recovering a saved list?
I have switched the function of the icon vs clicking on the link...
Clicking the link shows now the saved list, clicking that icon before the link should recover the selection.

I hope that this explanation solves this... changing an interface is always tricky....
Suggestions for more clear layout are welcome :-)

**Comment by rkhalil** [comment]
Hi Klap-in,

thank you very much for your quick reply, you are right, the interface changed slightly and I was too stupid to notice it :)

![dokuwiki_load_saved_selection](https://cloud.githubusercontent.com/assets/20515302/16941103/5f445e6c-4d8e-11e6-971b-05c202a308af.png)
