### ISSUE TITLE
Forbidden Pages has been output. 

### ISSUE THREAD

**Issue by jyagasaki** [Klap-in/dokuwiki-plugin-bookcreator#84]
Hi,

There are forbidden pages in load saved selection.
Forbidden pages isn't displayed in Selected Pages list.

However, these forbidden pages has been output.
I see the ”Skip Forbidden Pages” check box on the book screen, but it doesn't work.

Update is 2016-08-11.

Best regards,
Junko

**Comment by Klap-in** [comment]
What do you mean with 'has been output'?
That these pages are still included in your exported pdf? Or another output?

Which version of dw2pdf plugin is installed on your system?

**Comment by Klap-in** [comment]
Please update to the latest versions of DokuWiki, dw2pdf and bookcreator plugins.

If I export pages that are forbidden block the export with a popup explaining which pages are not allowed.

If you can still replicate this case, please share the ACL settings used for the forbidden page, such (a tested example or actual setup) that I can try to replicate in my setup for testing.
