### ISSUE TITLE
Unable to enter pages

### ISSUE THREAD

**Issue by michaelmontagne** [Klap-in/dokuwiki-plugin-bookcreator#85]
upon entering wiki:ebook page for the first time, the textbox under "Selected Pages" is not enabled.  I installed all required plugins.  The main wiki also has an issue with creating a new page so there may be a connection.

**Comment by Klap-in** [comment]
No idea which textbox you expect...
To select pages you have to go to that page and use there the appropriate buttons for select/deselect that page.

**Comment by michaelmontagne** [comment]
Ahh.  My bad.  I see that in the docs now.  But I do not see a toolbar on any pages.


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>

**Comment by Klap-in** [comment]
Which template are you using?
You have installed the last version of bookcreator?

**Comment by michaelmontagne** [comment]
I’m using the Dokuwiki template but it may have been modified previously.  I am transferring my wiki and upgrading in order to use you plugin.  I have the latest dokuwiki and the latest version of bookcreator.  Tried to install the arctic plugin from website and still no buttons.


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>

**Comment by michaelmontagne** [comment]
I see it!  It’s beautiful!  Output works great.  Is it possible to hide the “info” in the gray box at the bottom:


[cid:image001.png@01D21D8A.AF124C30]


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>

**Comment by Klap-in** [comment]
That pictures is not shown at Github, could you consider it uploading it there directly? Thanks

**Comment by michaelmontagne** [comment]
Not sure how to do that.  It might be part of the dw2pdf plugin.  It is a big box with a QR code along the right border (which I can disable) and three pieces of info along the left:
From:
Permanent Link:
Last update:


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>

**Comment by Klap-in** [comment]
Aha, you talk about the pdf that was created.
That block is in the 'default' template used by the dw2pdf plugin.

If you copy and rename that template, you can tuned that copied template according to your wishes. (A copy prevents overwriting on plugin update). In the configuration manager you can select your new template as preferred template.

**Comment by michaelmontagne** [comment]
Got it!   It's citation.html<http://citation.html>.   Working great now.   I'm going to poke around the config and template settings.   Fun!

mike montagne     opsis architecture
On Oct 3, 2016 3:54 PM, Gerrit Uitslag <notifications@github.com> wrote:

Aha, you talk about the pdf that was created.
That block is in the 'default' template used by the dw2pdf plugin.

If you copy and rename that template, you can tuned that copied template according to your wishes. (A copy prevents overwriting on plugin update). In the configuration manager you can select your new template as preferred template.

**Comment by michaelmontagne** [comment]
Gerrit,
One more issue.   My images are showing up as broken links in my exported pdfs.  They display correctly in dokuwiki.

1.        Are they supposed to display exported pdf?

2.       What troubleshooting steps would you recommend?


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>

**Comment by Klap-in** [comment]
Some time ago another issue is filled about images (see https://github.com/Klap-in/dokuwiki-plugin-bookcreator/issues/52). Seems not related, but maybe you see there ideas to test.

So far no clue why it happens. What happens if you export the `wiki:syntax` page? Are these pictures ok?
For certain pictures the GD library for PHP is required, is this library available?

**Comment by michaelmontagne** [comment]
It seems that.png images are not supported.  Jpegs work fine.  Naturally, all  my images are png.  But there aren’t really that many.  I’ll just redo them.


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>

**Comment by Klap-in** [comment]
Then my guess is that these png images have transparancy or are interlaced. This requires the GD library to be installed.

**Comment by michaelmontagne** [comment]
Impressive.  Absolutely correct.  Tax.


Mike Montagne, associate | technology guru | opsis architecture llp  | o:503.525.9511  d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com/>
