### ISSUE TITLE
Duplicate: Redirecting Links from wiki to pdf-pages

### ISSUE THREAD

**Issue by radicarl** [Klap-in/dokuwiki-plugin-bookcreator#88]
Hey,

it would be great, if links to wiki-pages which are also in the current book would link to the page in the pdf instead.

Sorry, duplicated to #16 
Pls Ignore/Close

**Comment by Klap-in** [comment]
You have the latest version of the plugins (dw2pdf and bookcreator) installed?
and you are still seeing that page in articles in de pdf are not correct referred to each other?

**Comment by radicarl** [comment]
Sorry, was my fault. I remebered that links were not redirect from a long time ago. Since then, we had an update of the dw2pdf plugin, but I create the pdfs only, don't have to work with them and did not noticed that this great feature was already implemented.
