### ISSUE TITLE
unknown link type on page tools

### ISSUE THREAD

**Issue by bartland** [Klap-in/dokuwiki-plugin-bookcreator#91]
Using the default DokuWiki Template
Bookcreator Plugin 2016-08-11
Dw2Pdf plugin 2016-04-17

Please see attached image

![unknown_link_type](https://cloud.githubusercontent.com/assets/10589082/19880028/64e39b28-a04d-11e6-9851-19d61ed31425.JPG)

**Comment by cmuller** [comment]
same here.. Fortunately the _Book Creator_ toolbar is working :)

**Comment by vladipus** [comment]
Same here =( Other plugins do work in the page tools panel.
![2017-03-29 11_13_25-wiki_ebook turbopedia](https://cloud.githubusercontent.com/assets/468323/24444924/d4147afc-1470-11e7-83d5-b644e188e038.png)

**Comment by Klap-in** [comment]
My impression is that this issue is solved. However I have made recently some other tweaks, and in near time some other tweaks will be released.. so if I broke something.. you know how to share the issue ;-)
