### ISSUE TITLE
"Add to book" icon missing in toolbar on some pages

### ISSUE THREAD

**Issue by LarsGit223** [Klap-in/dokuwiki-plugin-bookcreator#95]
I encountered the problem that on some pages the "Add to book" icon is missing.

For example if I copy the content of the wiki page DokuWiki features (see https://www.dokuwiki.org/features) into my wiki then everything is ok. If I go to that page I see the "Add to book" icon.

But if I copy the content of the wiki page DokuWiki syntax (see https://www.dokuwiki.org/wiki:syntax) into my wiki then the "Add to book" icon disappears when I enter/display the page.

Access right for the pages are the same. Also I am logged in as admin.

**Comment by LarsGit223** [comment]
This is only a configuration problem:
Under the bookcreator config setting **Don't show tools when ID contains** I had the option **wiki:syntax** activated. Deactivating the option enables/shows the button for the syntax page.

**Comment by Klap-in** [comment]
It was a feature, no bug  :1st_place_medal:   :-P

**Comment by LarsGit223** [comment]
Very simple indeed. A little bit embarrassing :blush:
