### ISSUE TITLE
A direct link to export a saved book

### ISSUE THREAD

**Issue by vladipus** [Klap-in/dokuwiki-plugin-bookcreator#97]
Would be nice to have this feature with a syntax like this:
```
~~SAVEDBOOK:namespace:page~~
```

**Comment by danb35** [comment]
Yes, this exactly.  Honestly, I'm surprised this doesn't already exist; it certainly seems to me like the most obvious way to use this plugin.  It's simple enough, I guess, to manually generate the PDF, and then link it somewhere, but then the PDF needs to be regenerated any time a page changes.

**Comment by Klap-in** [comment]
Indeed nice idea, to have a syntax that allows downloading the refered book. I propose only to support books as stored in the configured namespace (setting: `save_namespace`). I propose renaming to something that tell the action to expect from the syntax.

To accommodate some manners of writing, the following syntaxes should trigger the same download:
```
~~DOWNLOADBOOK: Nice saved book~~
~~DOWNLOADBOOK:nice_saved_book~~
~~DOWNLOADBOOK:wiki:ebook:nice_saved_book~~  (where wiki:ebook is the configured `save_namespace`)
```

If think already generating a book is not needed. For (on short time) repeated same requests the caching mechanism should already do its work.

**Comment by Klap-in** [comment]
This feature is implemented!

I changed the syntax another time. Not sure what is the best and most clear syntax:
```
~~EXPORTPDF:Saved namespace~~
~~EXPORTTEXT:saved_namespace~~
~~EXPORTHTML:saved namespace~~
~~EXPORTODT:saved namespace~~
```
Is someone read this, who did not write it on a wikipage, would it be clear enough that it is a saved selection from the bookcreator that is exported? With my current syntax it is clear what it will do, but maybe not so clear what the origin is.

**Comment by Juergen-aus-Zuendorf** [comment]
I have the same problem as vladipus and danb35, and I'm glad that there will be such a simple solution in the future.

Please also remember that you can now already specify parameters for the DW2PDF plugin during PDF creation, e.g. the name of the template. This should be supported by the new feature in any case. Example:
`... doku.php?id=wiki:ebook&tpl=mytemplate_de_v01&toc=1`

Best regards
Juergen

**Comment by Klap-in** [comment]
@Juergen-aus-Zuendorf additional url parameters should work.

please see https://www.dokuwiki.org/plugin:bookcreator#direct_export_a_saved_selection
(You need the latest dw2pdf and bookcreator versions. If you spot issues I like to hear.

**Comment by Juergen-aus-Zuendorf** [comment]
Very good, I haven't seen the new plugin version. It is not yet displayed in the Extension Manager.
But that's exactly what I wanted since a long time!

Made a small correction in the syntax info on your plugin page:
´´´
--EXPORTPDF:saved namespace?book_skipforbiddenpages=1--
--EXPORTPDF:saved namespace?book_skipforbiddenpages=1|Alternative title.pdf--
´´´
to 
´´´
--EXPORTPDF:saved namespace&book_skipforbiddenpages=1--
--EXPORTPDF:saved namespace&book_skipforbiddenpages=1|Alternative title.pdf--
´´´
("?" -> "&")

**Comment by Klap-in** [comment]
Implemented.
