### ISSUE TITLE
no pages selected

### ISSUE THREAD

**Issue by rattkin** [Klap-in/dokuwiki-plugin-bookcreator#98]
In the last update (2016-08-11) I can't export any pages - it says that "You don't have any pages selected yet." but I have loaded several past selections. Even If I make a new selections, no luck.
I have reverted to the older version 2016-07-27.zip for the meantime.
Latest chrome. Is it related to the localstorage changes?

**Comment by Klap-in** [comment]
Could be related of course. Did you have the latest version of both, dw2pdf and bookcreator plugins?

You see pages in the list with selected pages? 
Which browser are you using? (eventually you could have already a look at the Local Storage section of the developer tool of your browser)

So far I can not reproduce this. Please reopen if it is still an issue for you.
